### ISSUE TITLE
accompanying article is a dead link (404)

### ISSUE THREAD

**Issue by mepster** [sudharti/dropzone-rails-demo#3]
Beautiful demo... live on Heroku too!

The accompanying article linked here from your readme returns a 404:
http://sudharti.github.io/articles/dropzone-rails/

Thanks for the great demo, I have been tearing my hair out trying to get this to work!

**Comment by scaffeinate** [comment]
@mepster Moved the article to medium some time ago. Sorry about that. I have updated the link on the repo. Follow this one https://medium.com/rails-ember-beyond/ajax-file-upload-in-rails-using-dropzone-and-carrierwave-6f5436fdfdb0#.rvmq8edgt

**Comment by scaffeinate** [comment]
@mepster I am closing this issue. Thanks a lot 👍.
