### ISSUE TITLE
Problem: dropzone already attached. 

### ISSUE THREAD

**Issue by vahobrsti** [sudharti/dropzone-rails-demo#4]
Suggestion:
Your script sent too many post requests and does not give any feedback to the user. better to let the user know about the uploded file. 
![screenshot from 2016-05-16 00-36-39](https://cloud.githubusercontent.com/assets/13555885/15274789/82cd54c8-1afe-11e6-89b9-2daf04d54ca3.png)

**Comment by scaffeinate** [comment]
@vahobrsti I have fixed the issue

**Comment by scaffeinate** [comment]
@vahobrsti Also I have added alertify to show error and success logs. Thanks a lot for the awesome suggestion 👍. I am closing this issue now :)
